---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# suitestrings

<!-- badges: start -->

<!-- badges: end -->

This is primarily a learning project, for me to build my understanding of string manipulation and regular expressions (both using base R and popular packages) as well as how to create packages.

All suitestrings functionality is implemented in base R i.e. the functions are built as wrappers around base string manipulation functions. The interface mimics what's seen in [stringr](https://stringr.tidyverse.org/reference/index.html) and [stringi](https://stringi.gagolewski.com/rapi/stri_count.html), with the intent of being more readable and accessible.

So, the goal of suitestrings is to provide comprehensive set of functions for string manipulation and regular expression generation. Some notable features:

-   Consistent naming scheme - Designed for use with autocomplete with prefixes `str_` for vectorised operations over strings, `chr_` for operations on character vectors and `pattern_` for building regular expressions.

-   Order of inputs - suitestrings usually puts the string as the first argument instead of the pattern, which makes it easier to use with pipes than base R.

-   No additional dependencies - this package has no Imports and doesn't do anything you can't replicate exactly in base R.

## Installation

You can install the development version of suitestrings from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("davidfoord1/suitestrings")
```
